# Generated by Django 4.2 on 2023-04-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link_editor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logic',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logic', to='link_editor_app.question'),
        ),
    ]
