# Generated by Django 4.2 on 2023-04-05 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_editor_app', '0005_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logic',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=10),
        ),
    ]
