# Generated by Django 4.2 on 2023-04-06 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link_editor_app', '0006_alter_logic_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='logic',
            name='for_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logic_question', to='link_editor_app.question'),
        ),
    ]
